# Конфигурация бота

# Основные настройки бота 
Settings:
  Token: Null
  # Для работы LocalServer требуется скомпилированный сервер Telegram-Bot-API
  LocalServer: http://localhost:8081
  Company: Null
  Game: MetaverseRPG
  Internet: True
  Logging: False

# Настройки консоли
Console:
  Backlight: True

# Настройки аккаунта
Account:
  # Автоматический заход в аккаунт
  AutoLogin:
    TelegramID: Null
    Username: Null
