# Конфигурация бота

# Основные настройки бота 
Settings:
  Token: 6152495930:AAH-p-D4MHWTcmAg9WDEUiEicQbJEHHcL9o
  # Для работы LocalServer требуется скомпилированный сервер Telegram-Bot-API
  LocalServer: http://localhost:8081
  Company: Fruinity Project
  Game: MetaverseRPG
  Internet: True
  Logging: False

# Настройки консоли
Console:
  Backlight: True

# Настройки аккаунта
Account:
  # Автоматический заход в аккаунт
  AutoLogin:
    TelegramID: 1116769538
    Username: NekoNeto
